CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    PasswordUser VARCHAR(255) NOT NULL,
    profileimageURL VARCHAR(255)
);

CREATE TABLE Folders(
    FolderID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    FolderName VARCHAR(255) NOT NULL,
    ParentFolderID INT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (ParentFolderID) REFERENCES Folders(FolderID) ON DELETE SET NULL
);

CREATE TABLE Files (
    FileID INT PRIMARY KEY AUTO_INCREMENT,
    FolderID INT,
    UserID INT NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    FileType VARCHAR(50) NOT NULL,
    FileURL VARCHAR(255) NOT NULL,
    FOREIGN KEY (FolderID) REFERENCES Folders(FolderID) ON DELETE SET NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE Flashcards (
    FlashcardID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    Title VARCHAR(255) NOT NULL,
    FrontText TEXT NOT NULL,
    BackText TEXT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);




