# Generated by Django 5.0.4 on 2024-04-16 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_enrollment'),
        ('flashcards', '0003_alter_flashcard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
            preserve_default=False,
        ),
    ]
