# Generated by Django 4.2.11 on 2024-04-16 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friends')], default='PUBLIC', max_length=100)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('PDF', 'pdf'), ('DOC', 'doc'), ('DOCX', 'docx'), ('PPT', 'ppt'), ('PPTX', 'pptx'), ('XLS', 'xls'), ('XLSX', 'xlsx'), ('TXT', 'txt'), ('ZIP', 'zip'), ('JPG', 'jpg'), ('JPEG', 'jpeg'), ('PNG', 'png'), ('GIF', 'gif'), ('MP4', 'mp4'), ('MOV', 'mov'), ('AVI', 'avi'), ('MKV', 'mkv'), ('MP3', 'mp3'), ('WAV', 'wav'), ('FLAC', 'flac'), ('OGG', 'ogg'), ('FLASHCARD', 'flashcard'), ('OTHER', 'other')], default='OTHER', max_length=100)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FRIENDS', 'Friends')], default='PUBLIC', max_length=100)),
                ('parent_directory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
